### ISSUE TITLE
NameError: name 'STATE_PLAYING' is not defined

### ISSUE THREAD

**Issue by kriegy98** [IDmedia/hass-samsung_soundbar#6]
I have an error upon setting up this device for a Samsung HW-q90r. I get a 401 error when I go to the ip and port indicating the soundbar is working. 

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 446, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 702, in async_device_update
    await task
  File "/config/custom_components/samsung_soundbar/media_player.py", line 338, in async_update
    self._state = STATE_PLAYING
NameError: name 'STATE_PLAYING' is not defined

**Comment by kriegy98** [comment]
As an update, this error only appears when power options are set to false, setting it to true resolves the error.
